# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & Release

on:
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: CGO_ENABLED=0 go build -ldflags="-extldflags=-static" -o HFP *.go

    - name: Upload Release
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          release_config: |
              ./HFP
          tag_name: ${{ github.ref_name }}
          release_name: hfp ${{ github.ref_name }}
          draft: false
          prerelease: false
          overwrite: true    
